/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f407xx.h"

int main(void)
{
	//RCC
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	//GPIO
	GPIOD->MODER &= ~(3 << 22); //setting PD11 as an input

	GPIOD->MODER &= ~(3 << 24); //clearing PD12
	GPIOD->MODER |=  (1 << 24); //setting PD12 as an output for the LED

	GPIOD->MODER &= GPIO_PUPDR_PUPD11_Msk;
	GPIOD->MODER |= GPIO_PUPDR_PUPD11_1; //pull down resistor for PD11

	//NVIC
	NVIC_EnableIRQ(EXTI15_10_IRQn);//enabling exti11 at NVIC level

	//SYSCFG
	SYSCFG->EXTICR[3] |= SYSCFG_EXTICR3_EXTI11_PD;

	//RISING EDGE
	EXTI->RTSR |= EXTI_FTSR_TR11;

	//INTERRUPT MASK(Enable)
	//EXTI->IMR |= EXTI_IMR_MR11;

	while(1);


}

void EXTI15_10_IRQHandler (void){

	if((EXTI->PR & EXTI_PR_PR11) != 0){

		GPIOD->ODR |= GPIO_ODR_OD12;//turnng the led high

		//CLEAR THE PENDING BIT
		EXTI->PR |= EXTI_PR_PR11;
	}
}
